import {useState} from 'react';
import api from '../services/api';
import OfficerLogin from './OfficerLogin';
import './DataBridge.css';

const policy={'Identity Verification':['Citizen ID','Name','Citizenship Status'],'Address Verification':['Citizen ID','Address'],'Education Verification':['Citizen ID','Education'],'Tax Verification':['Citizen ID','Tax Status']};
const agencies={'Department of Transport Management':['Identity Verification','Address Verification'],'Local Government / Municipality':['Identity Verification','Address Verification'],'Department of Education':['Identity Verification','Education Verification'],'Inland Revenue Department':['Identity Verification','Tax Verification']};

export default function DataBridge(){
 const [purpose,setPurpose]=useState('Identity Verification'),[agency,setAgency]=useState('Department of Transport Management'),[citizenId,setCitizenId]=useState('CIT-2026-001'),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('databridge_user'))}catch{return null}});
 const fields=policy[purpose],allowed=agencies[agency].includes(purpose),all=['Citizen ID','Name','Citizenship Status','Address','Education','Tax Status'];
 const logout=(message='You have been signed out. Sign in to make a verification request.')=>{localStorage.removeItem('databridge_token');localStorage.removeItem('databridge_user');setUser(null);setResult(null);setError(message);window.dispatchEvent(new PopStateEvent('popstate'))};
 const verify=async e=>{e.preventDefault();if(!localStorage.getItem('databridge_token'))return setError('Please sign in as a Government Officer before verifying a citizen.');setLoading(true);setError('');try{const {data}=await api.post('/verification/request',{citizenId,purpose});setResult(data)}catch(err){setResult(null);if(err.status===401)return logout('Your session is invalid or expired. Please sign in again.');setError(err.status===403?`${err.message} This account or agency is not allowed to make this request.`:err.message||'Unable to complete verification.')}finally{setLoading(false)}};
 return <>
 <section className="bridge-hero" id="databridge"><div className="bridge-grid"/><div className="container bridge-intro"><div><span className="eyebrow">ACADEMIC PROTOTYPE / SIMULATION</span><h1>One Government.<br/><em>Connected Services.</em><br/>Trusted Data.</h1><p>A purpose-based interoperability layer that shares only the information an authorized agency needs—then lets the citizen see it.</p><div className="hero-actions"><a href="#verify" className="crimson-button">Open verification workspace →</a><a href="#how-it-works" className="plain-link">Explore the model</a></div></div><div className="flow-card"><span>01 · CITIZEN</span><i>↓</i><span>02 · GOVERNMENT DATA</span><i>↓</i><strong>03 · PURPOSE AUTHORIZATION</strong><i>↓</i><span>04 · AUTHORIZED AGENCY</span><i>↓</i><span>05 · AUDIT TRAIL</span></div></div></section>
 <section className="bridge-section" id="how-it-works"><div className="container"><span className="eyebrow dark">THE DATA MINIMIZATION MODEL</span><h2>Share the right data, for the right purpose.</h2><p className="lede">Records stay inside a simulated government repository. The requesting agency receives a deliberately filtered response—not the citizen’s complete profile.</p><div className="network"><div className="network-node citizen">Citizen<b>Aarav Sharma</b></div><div className="connector">→</div><div className="network-node repository">Government<b>Data Repository</b></div><div className="connector">→</div><div className="network-node policy">Purpose policy<b>{purpose}</b></div><div className="connector">→</div><div className="network-node authorized">Agency<b>{allowed?'AUTHORIZED':'NOT AUTHORIZED'}</b></div></div></div></section>
 <section className="workspace" id="verify"><div className="container workspace-grid"><div><span className="eyebrow dark">OFFICER WORKSPACE</span><h2>Purpose-based verification</h2><p>Each request is authenticated, checked against agency permissions, minimized at the API, and logged.</p>{!user?<OfficerLogin onLogin={setUser}/>:<><div className="signed-in">Signed in as <b>{user.name}</b> · <b>{user.role}</b><button type="button" onClick={()=>logout()}>Sign out</button></div>{error&&<p className="auth-error" role="alert">{error}</p>}<form onSubmit={verify} className="verification-form"><label>Requesting agency<select value={agency} onChange={e=>setAgency(e.target.value)}>{Object.keys(agencies).map(x=><option key={x}>{x}</option>)}</select></label><label>Citizen ID<input value={citizenId} onChange={e=>setCitizenId(e.target.value)} required/></label><label>Declared government purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)}>{Object.keys(policy).map(x=><option key={x}>{x}</option>)}</select></label><button className="crimson-button" disabled={loading}>{loading?'Verifying…':'Verify citizen →'}</button></form></>}</div><aside className="policy-panel"><span className={allowed?'status good':'status bad'}>{allowed?'✓ AUTHORIZED':'× NOT AUTHORIZED'}</span><h3>Fields this request can access</h3>{all.map(field=><div className={fields.includes(field)?'field on':'field'} key={field}><span>{fields.includes(field)?'✓':'—'}</span>{field}</div>)}<p className="policy-note">Authorization is evaluated before data is queried or returned.</p></aside></div></section>
 {result&&<section className="result-wrap"><div className="container"><div className="result-card"><div><span className="eyebrow dark">VERIFICATION COMPLETED</span><h2>Purpose-Limited Access</h2><p className="request-id">{result.requestId} · {purpose}</p><div className="data-grid">{Object.entries(result.data).map(([k,v])=><div key={k}><small>{k.replace(/([A-Z])/g,' $1')}</small><b>{v}</b></div>)}</div></div><div className="privacy-badge"><b>Privacy indicator</b><span>✓ {result.privacy.fieldsShared} fields shared</span><span>✓ {result.privacy.unrelatedFields} unrelated fields exposed</span><span>✓ Request logged</span><span>✓ Agency authorized</span></div></div></div></section>}
 <section className="security"><div className="container"><span className="eyebrow">SECURITY CONTROLS IMPLEMENTED IN THIS ACADEMIC PROTOTYPE</span><div className="security-list">{['JWT authentication','Role-based control','Purpose-limited access','Data minimization','Audit logging','Input validation'].map((x,i)=><div key={x}><b>0{i+1}</b>{x}</div>)}</div></div></section>
 </>;
}
